### PR TITLE
Script updates to make it work in one shot on Debian 8

### PR DESCRIPTION
**Pull request by kent1D**

### CODE REVIEW

**Comment by yohanboniface** [comment]
Thanks Quentin!
But note that, and I'm a bit annoyed to say that after you worked, at this time the preferred way to install ideasbox server is to use the ansible recipes: https://github.com/ideascube/ansiblecube :s

**Comment by kent1D** [comment]
Ah ah ah ;)

Don't worry

This project is really lacking documentation but people can't do everything coding / testing / documenting... 

I will try to contribute on this point these 2 next weeks

**Comment by yohanboniface** [comment]
> I will try to contribute on this point these 2 next weeks

\o/

About doc, you have http://ideascube.readthedocs.org/en/latest/ (but it's only the main application, not the whole server install).

**Comment by barbayellow** [comment]
There is some documentation on BsF' wiki : https://wiki.bsf-intranet.org/doku.php?id=ideascube:installation <- I made this one public. It's still a work on progress. We should publish it on the wiki here. English translation is needed though.

**Pull request merged**
